@startuml

[*] --> Idle : 正常
[*] --> ChangeState
Idle --> ChangeState
ChangeState --> NoConnect
[*] --> NoConnect : 通信エラー
Idle --> NoConnect : 通信エラー
NoConnect --> Idle : 通信回復\n状態の遷移は\nサーバーからの命令で\n行われる
ChangeState --> [*]
Idle --> [*]
NoConnect --> [*]

@enduml