@startuml
[*] --> Idle
note "IdleからCaughtByCatに遷移すると\n複雑になるので行わない" as N1
Idle --> Search : 通信が確立しているときのみ\n一定時間おきにイベント発生
Search --> Idle : No Detect
Search --> CaughtByCat
CaughtByCat --> Feed
Feed --> Idle
@enduml